title: "NS Performance Studio"
author: "NSopiha"
description: "NS Performance Studio offers personalized strength and conditioning programs in a motivating, community-driven environment."
permalink: /ns-performance-studio/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true
show_frame: true
show_sidebar: false
show_minimal: false

# Menu

navigation:
  - {file: "archive.html", sidebaricon: home}
  - {file: "README.md", sidebaricon: address-card}

external:
  - {title: Mail, icon: envelope, url: "mailto:nataliia.sopiha@calbrightcollege.org"}
  - {title: Github, icon: github, url: "https://github.com/nsopiha"}
 # - {title: Subscribe, icon: rss, url: "/"}#

comments:

#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
